# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('spclztn', models.CharField(max_length=20)),
                ('descp', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=15)),
                ('pswd', models.CharField(max_length=20)),
            ],
        ),
    ]
