# Generated by Django 5.1.1 on 2024-09-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='docDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('fees', models.PositiveIntegerField(blank=0, default=0)),
                ('experience', models.PositiveIntegerField(blank=0, default=0)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Landmark', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=15)),
                ('PIN', models.CharField(default='', max_length=6)),
                ('State', models.CharField(default='', max_length=15)),
                ('specialization', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=1000)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('slot1', models.BooleanField(default=False)),
                ('slot2', models.BooleanField(default=False)),
                ('slot3', models.BooleanField(default=False)),
                ('slot4', models.BooleanField(default=False)),
                ('slot5', models.BooleanField(default=False)),
                ('slot6', models.BooleanField(default=False)),
                ('slot7', models.BooleanField(default=False)),
                ('slot1_id', models.CharField(blank=True, default=0, max_length=19)),
                ('slot2_id', models.CharField(blank=True, default='', max_length=19)),
                ('slot3_id', models.CharField(blank=True, default='', max_length=19)),
                ('slot4_id', models.CharField(blank=True, default='', max_length=19)),
                ('slot5_id', models.CharField(blank=True, default='', max_length=19)),
                ('slot6_id', models.CharField(blank=True, default='', max_length=19)),
                ('slot7_id', models.CharField(blank=True, default='', max_length=19)),
                ('availibity', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_login.docdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor_login.appointment')),
            ],
        ),
    ]
