# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0002_auto_20171002_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdetails',
            name='slot1_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot2_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot3_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot4_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot5_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot6_id',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='docdetails',
            name='slot7_id',
            field=models.CharField(default='', max_length=19),
        ),
    ]
