# Generated by Django 5.1.1 on 2024-09-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0002_docdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docdetails',
            name='user',
        ),
    ]
