# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0004_auto_20171007_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdetails',
            name='slot1_id',
            field=models.CharField(default='', max_length=19),
        ),
    ]
