# Generated by Django 5.1.1 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0006_prescription_created_at_prescription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdetails',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='docdetails',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='docdetails',
            name='fees',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
