# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0009_auto_20171007_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdetails',
            name='slot8_id',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
    ]
