# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0011_remove_docdetails_slot8_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdetails',
            name='availibity',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
