# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0012_docdetails_availibity'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdetails',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
    ]
