# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0014_auto_20171027_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdetails',
            name='current_date',
            field=models.DateField(default=b'27102017', editable=False),
        ),
    ]
