# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 06:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(default=0)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(default=b'', max_length=6)),
                ('curr_booking', models.CharField(blank=True, default=b'', max_length=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
