# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='curr_booking',
        ),
    ]
