# Generated by Django 4.2 on 2023-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0007_auto_20171027_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='curr_booking_id',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
