# Generated by Django 4.2 on 2023-04-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0008_userprofile_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='booking_date',
            new_name='booked_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='curr_booking_id',
        ),
    ]
