# Generated by Django 5.1.1 on 2024-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0010_userprofile_curr_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='curr_booking_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
