# Generated by Django 5.1.1 on 2024-09-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0004_docdetails_user'),
        ('patient_login', '0011_alter_userprofile_curr_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='curr_booking_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latest_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_appointment', to='doctor_login.appointment'),
        ),
    ]
